<?php
App::uses('AppController', 'Controller');
/**
 * StoresProducts Controller
 *
 * @property StoresProduct $StoresProduct
 * @property PaginatorComponent $Paginator
 */
class StoresProductsController extends AppController {

/**
 * Components
 *
 * @var array
 */
	public $components = array('Paginator');

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->StoresProduct->recursive = 0;
		$this->set('storesProducts', $this->Paginator->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param string $id
 * @return void
 */
	public function view($id = null) {
		if (!$this->StoresProduct->exists($id)) {
			throw new NotFoundException(__('Invalid stores product'));
		}
		$options = array('conditions' => array('StoresProduct.' . $this->StoresProduct->primaryKey => $id));
		$this->set('storesProduct', $this->StoresProduct->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->StoresProduct->create();
			if ($this->StoresProduct->save($this->request->data)) {
				$this->Session->setFlash(__('The stores product has been saved.'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The stores product could not be saved. Please, try again.'));
			}
		}
		$stores = $this->StoresProduct->Store->find('list');
		$products = $this->StoresProduct->Product->find('list');
		$this->set(compact('stores', 'products'));
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param string $id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->StoresProduct->exists($id)) {
			throw new NotFoundException(__('Invalid stores product'));
		}
		if ($this->request->is(array('post', 'put'))) {
			if ($this->StoresProduct->save($this->request->data)) {
				$this->Session->setFlash(__('The stores product has been saved.'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The stores product could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('StoresProduct.' . $this->StoresProduct->primaryKey => $id));
			$this->request->data = $this->StoresProduct->find('first', $options);
		}
		$stores = $this->StoresProduct->Store->find('list');
		$products = $this->StoresProduct->Product->find('list');
		$this->set(compact('stores', 'products'));
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @param string $id
 * @return void
 */
	public function delete($id = null) {
		$this->StoresProduct->id = $id;
		if (!$this->StoresProduct->exists()) {
			throw new NotFoundException(__('Invalid stores product'));
		}
		$this->request->allowMethod('post', 'delete');
		if ($this->StoresProduct->delete()) {
			$this->Session->setFlash(__('The stores product has been deleted.'));
		} else {
			$this->Session->setFlash(__('The stores product could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
	
    
       	/**
		 * JSON API method
		 * generated by mcred/Cakeular Plugin
		 *
		 * @link          https://github.com/mcred/Cakeular
		 *
		 * @return void
		 * @throws exception
		 */
		public function api($id = null)
		{
            Configure::write('debug', 0);
            $this->autoRender = false;
            $this->layout = 'ajax';
            
            
            $response = array(
                'success' => false,
                'message' => 'No Action',
                'xData' => array()
            );

			switch ($this->request->method())
			{
				case 'GET':
					if (!$id)
					{
						if( isset($this->request->query["parent_field"]) && isset($this->request->query["parent_value"]) )
						{
							try {
								$parentField = $this->request->query["parent_field"];
								$parentValue = $this->request->query["parent_value"];

								$this->StoresProduct->recursive = -1;
								$storesproducts = $this->StoresProduct->find('all', array(
									'conditions' => array(
										'StoresProduct.'. $parentField . ' LIKE ' => '%' . $parentValue . '%'
									)
								));
								
                                $response = array(
                                    'success' => true,
                                    'message' => 'OK',
                                    'xData' => $storesproducts
                                );
								echo json_encode($response);
								return;
							}
							catch(Exception $ex)
							{
                                $response = array(
                                    'success' => false,
                                    'message' => $ex->getMessage(),
                                    'xData' => array()
                                );
                                echo json_encode($response);
                                return;
							}
						} 
						else {
						    $storesproducts = $this->StoresProduct->find('all', array());
                            $response = array(
                                'success' => true,
                                'message' => 'OK',
                                'xData' => $storesproducts
                            );
							echo json_encode($response);
							return;
						}

					} elseif(!$this->StoresProduct->exists($id))
					{
                        $response = array(
                            'success' => false,
                            'message' => __('El producto no fue encontrado en el inventario'),
                            'xData' => array()
                        );
                        echo json_encode($response);
                        return;
					} else
					{
						$storesproduct = $this->Account->find('first', array('conditions' => array('StoresProduct.' . $this->StoresProduct->primaryKey => $id)));
                        $response = array(
                            'success' => true,
                            'message' => 'OK',
                            'xData' => $storesproduct
                        );
                        echo json_encode($response);
                        return;
					}
					break;
				case 'POST':
					if(!isset($this->request->data['body']))
					{
                        $response = array(
                            'success' => false,
                            'message' => __('Los datos del POST no fueron encontrados'),
                            'xData' => array()
                        );
                        echo json_encode($response);
                        return;
					}
					$this->StoresProduct->create();
					try
					{
						if ( $this->StoresProduct->save( $this->request->data['body'] ) )
						{
						    $storesproduct = $this->StoresProduct->read(null, $this->StoresProduct->getLastInsertID());
							
                            $response = array(
                                'success' => true,
                                'message' => __('El producto fue guardado en el inventario'),
                                'xData' => $storesproduct
                            );
                            echo json_encode($response);
                            return;
                            
						} else
						{
                            $response = array(
                                'success' => false,
                                'message' => __('El producto no fue guardado en el inventario'),
                                'xData' => $this->StoresProduct->validationErrors
                            );
                            echo json_encode($response);
                            return;
						}
					}
					catch(Exception $ex)
					{
                        $response = array(
                            'success' => false,
                            'message' => $ex->getMessage(),
                            'xData' => array()
                        );
                        echo json_encode($response);
                        return;
					}					
					break;
				case 'PUT':
					if(!$id)
					{
                        $response = array(
                            'success' => false,
                            'message' => __('EL parametro ID no fue encontrado'),
                            'xData' => array()
                        );
                        echo json_encode($response);
                        return;
						break;
					}
					if(!isset($this->request->data['body']))
					{
                        $response = array(
                            'success' => false,
                            'message' => __('Los datos del POST no fueron encontrados'),
                            'xData' => array()
                        );
                        echo json_encode($response);
                        return;
						break;
					}
					try {
						if ( $this->StoresProduct->save( $this->request->data['body'] ) )
						{
						    $storesproduct = $this->StoresProduct->read(null, $this->request->data['body']["id"]);
                            $response = array(
                                'success' => true,
                                'message' => __('El producto fue actualizado en el inventario'),
                                'xData' => $storesproduct
                            );
                            echo json_encode($response);
                            return;
						} else
						{
                            $response = array(
                                'success' => false,
                                'message' => __('El producto no fue guardado en el inventario'),
                                'xData' => $this->StoresProduct->validationErrors
                            );
                            echo json_encode($response);
                            return;
						}
					}
					catch(Exception $ex)
					{
                        $response = array(
                            'success' => false,
                            'message' => $ex->getMessage(),
                            'xData' => array()
                        );
                        echo json_encode($response);
                        return;
					}					
					break;
				case 'DELETE':
					if(!$id)
					{
                        $response = array(
                            'success' => false,
                            'message' => __('EL parametro ID no fue encontrado'),
                            'xData' => array()
                        );
                        echo json_encode($response);
                        return;
					}
					$this->StoresProduct->id = $id;
					if ($this->StoresProduct->delete())
					{
                        $response = array(
                            'success' => true,
                            'message' => __('El producto fue eliminado del inventario'),
                            'xData' => array()
                        );
                        echo json_encode($response);
                        return;
					} else
					{
                        $response = array(
                            'success' => true,
                            'message' => __('El producto no fue eliminado del inventario'),
                            'xData' => array()
                        );
                        echo json_encode($response);
                        return;
					}
					break;
				default:
                    $response = array(
                        'success' => false,
                        'message' => 'Invalid Request Method',
                        'xData' => array()
                    );
                    echo json_encode($response);
                    return;
			}
		}

}
